server:
  port: 8083
spring:
  application:
    name: "franquicia"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  data:
    mongodb:
      uri: "mongodb+srv://dairo3rincon:fUd0bCEdBY8TtBBl@cluster0.wfuqmsj.mongodb.net/db_prueba?retryWrites=true&w=majority"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8083, http://localhost:8080"
